name: Deploy ML API 

on: 
  push: 
    branches:
      - master
    
jobs:
  deploy:
    runs-on: ubuntu-latest
  steps: 

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli 
      uses: google-github-actions/setup-gcloud@v0
      with: 
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: build and push docker image
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        REGION: ${{ secrets.REGION }}
      run: |
        gcloud auth configure-docker $REGION-docker.pkg.dev
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/api-to-predict-app:latest
        docker push -docker.pkg.dev/$PROJECT_ID/api-to-predict-app:latest
        gcloud run deploy api-to-predict-app --image gcr.io/$PROJECT_ID/api-to-predict-app --region $REGION --allow-unauthenticated