name: DEPLOY GCP

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    environment: prd
    env:
      IMAGE_NAME: gcr.io/${{ secrets.PROJECT_ID }}/my-service:latest
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Login to GCP
      - uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.PROJECT_ID }}

      # Auth to GCP
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # gcloud configure
      - name: Configure Credentials
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}

      # Build Docker image
      - name: Build Docker image
        run: gcloud builds submit --tag $IMAGE_NAME

      # Deploy Docker image to Cloud Run
      - name: Deploy Docker image to Cloud Run
        run: gcloud run deploy my-service --image="$IMAGE_NAME" --region="us-central1" --memory 528Mi --min-instances 0 --max-instances 1 --allow-unauthenticated