name: Deploy ML API

on:
  pull_request:
    branches:
      - master
  workflow_run:
    workflows: [Creating CI/CD]
    types:
      - completed
  push:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-to-predict-app:v${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/api-to-predict-app:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: ${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Fetch deployed URL
        run: |
          deployed_url="${{ steps.deploy.outputs.url }}"
          echo "Deployed URL: $deployed_url"
          curl "$deployed_url"