name: DEPLOY GCP

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    environment: prd
    env:
      IMAGE_NAME: gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE }}:latest
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Login to GCP
      - uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.PROJECT_ID }}

      # gcloud configure docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # Build Docker image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      # Tag Docker image with GCR URI
      - name: Tag Docker image
        run: docker tag $IMAGE_NAME $IMAGE_NAME

      # Push Docker image to Container Registry
      - name: Push Docker image
        run: docker push $IMAGE_NAME

      # Deploy Docker image to Cloud Run
      - name: Deploy Docker image to Cloud Run
        run: gcloud run deploy ${{ env.SERVICE }} --image $IMAGE_NAME --region us-central1 --memory 128Mi --min-instances 0 --max-instances 1 --platform managed --port 80 --allow-unauthenticated