name: Deploy ML API 


on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.PROJECT_ID }}
        SERVICE_NAME: ${{ env.SERVICE }}
        REGION: ${{ env.REGION }}
      run: |
        gcloud auth configure-docker $REGION-docker.pkg.dev
        docker build -t $REGION-docker.pkg.dev/$GOOGLE_PROJECT/demo/$SERVICE_NAME:latest .
        docker push $REGION-docker.pkg.dev/$GOOGLE_PROJECT/demo/$SERVICE_NAME:latest
        gcloud run deploy api-to-predict-app --image gcr.io/$PROJECT_ID/api-to-predict-app --region $REGION --allow-unauthenticated