name: Deploy ML API

on:
  pull_request:
    branches:
      - master
  workflow_run:
    workflows: [Creating CI/CD]
    types:
      - completed
  push:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-to-predict-app:v${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/api-to-predict-app:latest

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/api-to-predict-app/api-to-predict-app:latest

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'